name: Test Workflow with Fake Secrets

on: [push]

env:
  AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
  AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  GITHUB_TOKEN: ghp_a1b2c3d4e5f6g7h8i9j0klmnopqrstuvwx
  SLACK_WEBHOOK_URL: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX
  DATABASE_URL: postgres://admin:SuperSecretPass123@db.example.com:5432/mydatabase
  DOCKERHUB_PASSWORD: p@ssw0rd1234567890

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print AWS keys (this would be bad in real life)
        run: |
          echo "AWS Key ID: $AWS_ACCESS_KEY_ID"
          echo "AWS Secret: $AWS_SECRET_ACCESS_KEY"
      
      - name: Call internal API with token
        run: |
          curl -H "Authorization: Bearer sk_test_4eC39HqLyjWDarjtT1zdp7dc" https://internal.api.company.com/secret

      - name: Upload artifact with credentials file
        run: |
          echo "username=admin" > creds.txt
          echo "password=SuperUltraSecret!" >> creds.txt
          echo "api_key=abcd1234efgh5678ijkl" >> creds.txt
          echo "PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BA...\n-----END PRIVATE KEY-----" >> creds.txt
          gh actions upload-artifact --name credentials --path creds.txt

      - name: Export some env manually
        run: |
          export MY_SECRET_API_KEY=12345-ABCDE-67890-FGHIJ
          export STRIPE_SECRET_KEY=sk_live_51H8xQaL2EXAMPLEKEY
